src/cxsc.C
src/fplll.C
src/mpc.c
src/mpd.c
src/mpfi.c
src/mpfr.c

This replaces a lot includes of GAP headers by a single include of the `compiled.h` header.
This has the advantage that it will keep working even if we rename kernel header files -- and in fact, just that happened recently (`string.h` was renamed to `stringobj.h` by @markuspf for good reasons), which broke compilation of `float`.
With this patch, `float` should compile fine with past, present and future versions of GAP.

Use GAP's compiled.h header

---

tst/Makefile.am

Description: fix automake machinery for tst
Origin: vendor, Debian
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2017-06-02

Update automake file t/Makefile.am: add fplll.tst

---

lib/pslq.gi

MutableIdentityMat has been obsolete since GAP 4.1 or so.
BTW, this file is using windows line ends, you may want to change that?

Replace obsolete MutableIdentityMat

---

src/float.c

Assigning to `TYPE_DATOBJ` will at some point in the future lead to a compiler error, as we will make its return value `const`.

Use SET_TYPE_DATOBJ to set type of a T_DATOBJ

---

tst/arithmetic.tst
tst/testall.g

This helps the GAP team automate tracking regressions in packages,
e.g. caused by work on GAP itself.

tst/testall.g: indicate test status via exit code

---

Makefile.am
configure.ac
m4/ac_check_cxsc.m4
m4/ac_check_fplll.m4
m4/ac_check_mpc.m4
m4/ac_check_mpfi.m4
m4/ac_check_mpfr.m4

With this commit, float now correctly detects the absence / presence
of its external dependencies, and allows a user who only has a subset
of them installed to compile float anyway. Previously, you either had
to have them all; or if not, then manually use --without-cxsx etc.
This resolves issue #24

Remove remaining code for building things in extern/

---

PackageInfo.g
README.md

This better renders it on GitHub and GitHub pages and properly displays Travis and CodeCov badges.

Convert README to markdown

---

.travis.yml
m4/ac_find_gap.m4
src/float.c

* drop CONFIGNAME support
* make it possible to compile against future GAP releases with
compatibility mode turned off

Modernize ac_find_gap.m4

---

src/floattypes.h

Since GAP 4.9, GAP always uses GMP to implement integers, so there is no point
in checking for USE_GMP. In fact, GAP only retained this define to allow the
float package to keep working. It'd be nice if we could remove it in GAP 4.11.

Stop using USE_GMP

---

COPYING
PackageInfo.g
README.md

The manual claimed the license was GPL 2 or later; the README
that it was GPL 3 or later. Changed everything to the former,
which is in line with the license used by GAP itself.
Let me know you prefer to keep it at GPL 3 or later, then I'll adapt the PR accordingly. It's just that I had to pick one to make this PR, and we have a slight preference for GPL >=2, as that removes one more licensing hassle for packagers.

Clarify license, add License field to PackageInfo.g

---

src/cxsc.C
src/floattypes.h
src/mpc.c
src/mpd.c
src/mpfi.c
src/mpfr.c

In GAP 4.11, most uses of ErrorReturnObj were removed, and in GAP 4.12
all of them. Background is that we found that it is extremely hard for
users to use them correctly, but incorrect use quickly leads to crashes,
or worse (nonsense results of computations). Based on some informal
polling, we found nobody who actually uses this feature other than in
extremely rare fringe cases, and nobody actually expressed any regret
about removing this feature.
Note that ErrorReturnVoid for now still is possible, there are a few
cases where it's useful, but we also suggest to minimize usage of that.

Avoid using ErrorReturnObj

---

src/mpfr.c

The GAP headers used to be very generous in which system headers they
included. This has been reduced on GAP master, and in general, it is a good
idea if code explicitly includes all headers it needs, instead of relying on
indirect includes to provide them.

Fix warning: implicitly declaring library function 'isdigit'

---

PackageInfo.g
read.g

Banner before this patch:
Loading modules [mpfr, mpfi, mpc, fplll] for float 0.9.9 ...
Banner after this patch:
─────────────────────────────────────────────────────────────
Loading  float 0.9.9 (Floating-point numbers)
by Laurent Bartholdi (http://www.uni-math.gwdg.de/laurent).
Loaded modules: mpfr, mpfi, mpc, fplll
Homepage: https://gap-packages.github.io/float/
Report issues at https://github.com/gap-packages/float/issues
─────────────────────────────────────────────────────────────

Change package banner to use BannerFunction

---

.github/workflows/CI.yml
src/float.c

The removed code was there just to support these older GAP versions

Drop GAP 4.9 & 4.10 from CI, and remove some code

---

m4/ac_check_fplll.m4

It is not used, and clashes with a define in fplll.h

Don't define FPLLL_VERSION

---

src/cxsc.C
src/mpc.c
src/mpd.c

This is a selection of fixes for pointers being kept over GCes.
This replaces (and extends) #68 . That is the most complicated of the fixes, I'm happy to pull it out into another PR if requested.

Assorted memory fixes

---

src/cxsc.C
src/cxsc_poly.C
src/cxsc_poly.h
src/float.c
src/floattypes.h
src/fplll.C
src/mpc.c
src/mpfi.c
src/mpfr.c

- add include guards
- let it include gmp.h as it requires it
- let it include GAP headers, as it needs them; and since we now
require GAP 4.11, also change the header included for that from
`src/compiled.h` to `gap_all.h`
- move `cpoly_CXSC` declaration to its own header file, to avoid annoying
include order shenanigans

Improve floattypes.h, cleanup

---

m4/ac_check_cxsc.m4
m4/ac_check_fplll.m4
m4/ac_check_mpc.m4
m4/ac_check_mpfi.m4
m4/ac_check_mpfr.m4
src/Makefile.am

Without this, using a "manually" installed MPC does not work, as the required `-I` flags never reached the compiler. Similar for the `-L` flags for MPFR

Fix CFLAGS/LDFLAGS/CPPFLAGS

---

src/mpfr.c

Calling NEW_PLIST may move g, rending the later call to MPFR_OBJ(g) invalid

Fix potential GC crash in EXTREPOFOBJ_MPFR

---

src/cpoly.C
src/cxsc_poly.C
src/cxsc_poly.h
src/mpc.c

I attempted to build version 1.0.1 for Fedora.  We build with C-XSC support.  The build failed like this:
```
cxsc_poly.C:18:15: error: conflicting declaration of 'int cpoly_CXSC(int, const cxsc::complex*, cxsc::complex*, int)' with 'C' linkage
18 | #define cpoly cpoly_CXSC
|               ^~~~~~~~~~
cpoly.C:339:16: note: in expansion of macro 'cpoly'
339 | extern "C" int cpoly(int degree, const xcomplex *poly, xcomplex *Roots, int prec)
|                ^~~~~
In file included from cxsc_poly.C:16:
cxsc_poly.h:1:5: note: previous declaration with 'C++' linkage
1 | int cpoly_CXSC(int degree, const cxsc::complex coeffs[], cxsc::complex roots[], int prec);
|     ^~~~~~~~~~
```
The first commit in this series fixes that by removing the `extern "C"`.  I was able to build with support for all of …

Fix compiler errors and warnings with C-XSC support

---

Makefile.am
configure.ac
src/Makefile.am

This patch fixes up building + running float on Cygwin. I'm happy to explain all the bits, but this is basically what we do in other packages, such as semigroups.
With this patch (I hope) float should be fully functional in the next GAP windows release, using libmpc & libmpfr (as those packages are already packaged with cygwin, unlike mpfr and fplll).

Fix building on Cygwin

---

src/cxsc.C

The Fedora project has started using GCC 12 (not yet released generally) to build packages.  I did a build of float 1.0.3 this morning, and saw these warnings:
```
cxsc.C: In function 'pow(cxsc::real&, cxsc::complex&)':
cxsc.C:860:15: warning: infinite recursion detected [-Winfinite-recursion]
860 | cxsc::complex pow(cxsc::real &a, cxsc::complex &b) { return pow(a,b); }
|               ^~~
cxsc.C:860:64: note: recursive call
860 | cxsc::complex pow(cxsc::real &a, cxsc::complex &b) { return pow(a,b); }
|                                                             ~~~^~~~~
cxsc.C: In function 'pow(cxsc::real&, cxsc::interval&)':
cxsc.C:861:16: warning: infinite recursion detected [-Winfinite-recursion]
861 | cxsc::interval pow(cxsc::real &a, cxsc::interval &b) { return pow(a,b); }
| …
```

Use explicit conversions when calling cxsc::pow()

---

doc/float.xml

- the canonical GAP website URL is www.gap-system.org
- update link to package manual PDF on GAP website

Update some links in the manual

---

m4/ac_check_fplll.m4
src/fplll.C

Description: fix fplll namespace issue
Upstream maintainer of FPLLL has removed from `root` fplll.h
'using namespace fplll' (commit e886a8899f71ca78711fdf420e6817432b2fe4be),
this patch mimics the former behviour at the scale of this package.
Origin: vendor, Debian
Author: Jerome Benoit <calculus@rezozer.net>
Last-Update: 2022-07-03

fplll: fix namespace issue

---

configure.ac

It serves no purpose but is just one more place one has
to remember to update for releases.

configure.ac: don't hardcode package version

---

.github/workflows/CI.yml

GitHub no longer offers ubuntu-18.04 runners

CI: fix 32bit builds

---

src/cxsc.C

The `set_unexpected` function was deprecated in C++11, and has been removed entirely in C++17.  The default action when an uncaught exception is thrown is terminate, so the existing `set_terminate` call handles that case.

Remove use of deprecated set_unexpected

---

src/cxsc.C
src/fplll.C

`ObjFunc` is already defined in gap's common.h.  The redundant definitions become an issue if the gap definition changes, as suggested in https://github.com/gap-system/gap/issues/5857, making them fail to match.

Remove redundant definitions of ObjFunc
